version: "3.8"

services:
  queue:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  apiserver:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - QUEUE_HOST=queue
      - QUEUE_PORT=5672
    depends_on:
      - queue